// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';
import {main} from '../models';

export function CheckUpdate():Promise<boolean>;

export function GetMissingDLC():Promise<Array<process.IncompleteTitle>>;

export function GetMissingGames():Promise<Array<main.SwitchTitle>>;

export function GetMissingUpdates():Promise<Array<process.IncompleteTitle>>;

export function IsKeysFileAvailable():Promise<boolean>;

export function LoadSettings():Promise<string>;

export function OrganizeLibrary():Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function UpdateDB():Promise<void>;

export function UpdateLocalLibrary(arg1:boolean):Promise<main.LocalLibraryData>;

export function UpdateProgress(arg1:number,arg2:number,arg3:string):Promise<void>;
