// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetMissingDLC() {
  return window['go']['main']['App']['GetMissingDLC']();
}

export function GetMissingGames() {
  return window['go']['main']['App']['GetMissingGames']();
}

export function GetMissingUpdates() {
  return window['go']['main']['App']['GetMissingUpdates']();
}

export function IsKeysFileAvailable() {
  return window['go']['main']['App']['IsKeysFileAvailable']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OrganizeLibrary() {
  return window['go']['main']['App']['OrganizeLibrary']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdateDB() {
  return window['go']['main']['App']['UpdateDB']();
}

export function UpdateLocalLibrary(arg1) {
  return window['go']['main']['App']['UpdateLocalLibrary'](arg1);
}

export function UpdateProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2, arg3);
}
