name: "Setup Environment"
description: Setup the environment for compiling the solution
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

    - name: Install Wails
      shell: bash
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
