name: "Setup Environment"
description: Setup the environment for compiling the solution
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Get bundler
      working-directory: ./src
      shell: bash
      run: go get -u github.com/firebat20/go-astilectron-bundler/

    - name: Install bundler
      working-directory: ./src
      shell: bash
      run: go install github.com/firebat20/go-astilectron-bundler/astilectron-bundler

    - name: Move bundler
      working-directory: ./src
      shell: bash
      run: mv $HOME/go/bin/astilectron-bundler .
