name: Build master

on:
  push:
    branches:
     - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      uses: ./.github/actions/setup-environment

    - name: Build app
      run: |
        wails build

    - name: Publish artifacts
      uses: ./.github/actions/publish-artifacts
