name: Build

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build app
        uses: ./.github/actions/build-app

      - name: Publish artifacts
        uses: ./.github/actions/publish-artifacts
