name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build app
        id: build
        uses: ./.github/actions/build-app

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src/output/windows-amd64/*
            src/output/linux-amd64/*
            src/output/darwin-amd64/*
