name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build app
        id: build
        uses: ./.github/actions/build-app

      - name: Package artifacts
        run: |
          # Create a directory to hold the packaged files
          mkdir release_packages

          # Package Windows artifact as a zip
          (cd src/output/windows-amd64 && zip -r ../../../release_packages/switch-library-manager.windows-amd64.zip *)
          
          # Package Linux artifact as a tar.gz
          (cd src/output/linux-amd64 && tar -czf ../../../release_packages/switch-library-manager.linux-amd64.tar.gz *)

          # Package Mac artifact as a zip
          (cd src/output/darwin-amd64 && zip -r ../../../release_packages/switch-library-manager.darwin-amd64.zip *)

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: release_packages/*
